/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosUsoRouteImport } from './routes/termos-uso'
import { Route as ProdutoresRouteImport } from './routes/produtores'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as MeusInteressesRouteImport } from './routes/meus-interesses'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoraSlugRouteImport } from './routes/produtora.$slug'
import { Route as ProdutorSlugRouteImport } from './routes/produtor.$slug'
import { Route as BeatSlugRouteImport } from './routes/beat.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectedRouteRouteImport } from './routes/admin/_protected/route'
import { Route as AdminProtectedUsuariosRouteImport } from './routes/admin/_protected/usuarios'
import { Route as AdminProtectedProdutorasRouteImport } from './routes/admin/_protected/produtoras'
import { Route as AdminProtectedLeadsRouteImport } from './routes/admin/_protected/leads'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin/_protected/dashboard'
import { Route as AdminProtectedConfiguracoesRouteImport } from './routes/admin/_protected/configuracoes'
import { Route as AdminProtectedBeatsRouteImport } from './routes/admin/_protected/beats'

const TermosUsoRoute = TermosUsoRouteImport.update({
  id: '/termos-uso',
  path: '/termos-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresRoute = ProdutoresRouteImport.update({
  id: '/produtores',
  path: '/produtores',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusInteressesRoute = MeusInteressesRouteImport.update({
  id: '/meus-interesses',
  path: '/meus-interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProdutoraSlugRoute = ProdutoraSlugRouteImport.update({
  id: '/produtora/$slug',
  path: '/produtora/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorSlugRoute = ProdutorSlugRouteImport.update({
  id: '/produtor/$slug',
  path: '/produtor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatSlugRoute = BeatSlugRouteImport.update({
  id: '/beat/$slug',
  path: '/beat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProtectedRouteRoute = AdminProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProtectedUsuariosRoute = AdminProtectedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedProdutorasRoute =
  AdminProtectedProdutorasRouteImport.update({
    id: '/produtoras',
    path: '/produtoras',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedLeadsRoute = AdminProtectedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedConfiguracoesRoute =
  AdminProtectedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedBeatsRoute = AdminProtectedBeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/produtores': typeof ProdutoresRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/beat/$slug': typeof BeatSlugRoute
  '/produtor/$slug': typeof ProdutorSlugRoute
  '/produtora/$slug': typeof ProdutoraSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/beats': typeof AdminProtectedBeatsRoute
  '/admin/configuracoes': typeof AdminProtectedConfiguracoesRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/produtoras': typeof AdminProtectedProdutorasRoute
  '/admin/usuarios': typeof AdminProtectedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/produtores': typeof ProdutoresRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/beat/$slug': typeof BeatSlugRoute
  '/produtor/$slug': typeof ProdutorSlugRoute
  '/produtora/$slug': typeof ProdutoraSlugRoute
  '/admin/beats': typeof AdminProtectedBeatsRoute
  '/admin/configuracoes': typeof AdminProtectedConfiguracoesRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/produtoras': typeof AdminProtectedProdutorasRoute
  '/admin/usuarios': typeof AdminProtectedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/produtores': typeof ProdutoresRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/_protected': typeof AdminProtectedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/beat/$slug': typeof BeatSlugRoute
  '/produtor/$slug': typeof ProdutorSlugRoute
  '/produtora/$slug': typeof ProdutoraSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_protected/beats': typeof AdminProtectedBeatsRoute
  '/admin/_protected/configuracoes': typeof AdminProtectedConfiguracoesRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/leads': typeof AdminProtectedLeadsRoute
  '/admin/_protected/produtoras': typeof AdminProtectedProdutorasRoute
  '/admin/_protected/usuarios': typeof AdminProtectedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/meus-interesses'
    | '/politica-privacidade'
    | '/produtores'
    | '/termos-uso'
    | '/admin/login'
    | '/beat/$slug'
    | '/produtor/$slug'
    | '/produtora/$slug'
    | '/admin/'
    | '/admin/beats'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/produtoras'
    | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/como-funciona'
    | '/meus-interesses'
    | '/politica-privacidade'
    | '/produtores'
    | '/termos-uso'
    | '/admin'
    | '/admin/login'
    | '/beat/$slug'
    | '/produtor/$slug'
    | '/produtora/$slug'
    | '/admin/beats'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/produtoras'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/meus-interesses'
    | '/politica-privacidade'
    | '/produtores'
    | '/termos-uso'
    | '/admin/_protected'
    | '/admin/login'
    | '/beat/$slug'
    | '/produtor/$slug'
    | '/produtora/$slug'
    | '/admin/'
    | '/admin/_protected/beats'
    | '/admin/_protected/configuracoes'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/leads'
    | '/admin/_protected/produtoras'
    | '/admin/_protected/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRoute: typeof AppRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  MeusInteressesRoute: typeof MeusInteressesRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  ProdutoresRoute: typeof ProdutoresRoute
  TermosUsoRoute: typeof TermosUsoRoute
  BeatSlugRoute: typeof BeatSlugRoute
  ProdutorSlugRoute: typeof ProdutorSlugRoute
  ProdutoraSlugRoute: typeof ProdutoraSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-uso': {
      id: '/termos-uso'
      path: '/termos-uso'
      fullPath: '/termos-uso'
      preLoaderRoute: typeof TermosUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores': {
      id: '/produtores'
      path: '/produtores'
      fullPath: '/produtores'
      preLoaderRoute: typeof ProdutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-interesses': {
      id: '/meus-interesses'
      path: '/meus-interesses'
      fullPath: '/meus-interesses'
      preLoaderRoute: typeof MeusInteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produtora/$slug': {
      id: '/produtora/$slug'
      path: '/produtora/$slug'
      fullPath: '/produtora/$slug'
      preLoaderRoute: typeof ProdutoraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor/$slug': {
      id: '/produtor/$slug'
      path: '/produtor/$slug'
      fullPath: '/produtor/$slug'
      preLoaderRoute: typeof ProdutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beat/$slug': {
      id: '/beat/$slug'
      path: '/beat/$slug'
      fullPath: '/beat/$slug'
      preLoaderRoute: typeof BeatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_protected/usuarios': {
      id: '/admin/_protected/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminProtectedUsuariosRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/produtoras': {
      id: '/admin/_protected/produtoras'
      path: '/produtoras'
      fullPath: '/admin/produtoras'
      preLoaderRoute: typeof AdminProtectedProdutorasRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/leads': {
      id: '/admin/_protected/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminProtectedLeadsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/configuracoes': {
      id: '/admin/_protected/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminProtectedConfiguracoesRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/beats': {
      id: '/admin/_protected/beats'
      path: '/beats'
      fullPath: '/admin/beats'
      preLoaderRoute: typeof AdminProtectedBeatsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
  }
}

interface AdminProtectedRouteRouteChildren {
  AdminProtectedBeatsRoute: typeof AdminProtectedBeatsRoute
  AdminProtectedConfiguracoesRoute: typeof AdminProtectedConfiguracoesRoute
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedLeadsRoute: typeof AdminProtectedLeadsRoute
  AdminProtectedProdutorasRoute: typeof AdminProtectedProdutorasRoute
  AdminProtectedUsuariosRoute: typeof AdminProtectedUsuariosRoute
}

const AdminProtectedRouteRouteChildren: AdminProtectedRouteRouteChildren = {
  AdminProtectedBeatsRoute: AdminProtectedBeatsRoute,
  AdminProtectedConfiguracoesRoute: AdminProtectedConfiguracoesRoute,
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedLeadsRoute: AdminProtectedLeadsRoute,
  AdminProtectedProdutorasRoute: AdminProtectedProdutorasRoute,
  AdminProtectedUsuariosRoute: AdminProtectedUsuariosRoute,
}

const AdminProtectedRouteRouteWithChildren =
  AdminProtectedRouteRoute._addFileChildren(AdminProtectedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminProtectedRouteRoute: typeof AdminProtectedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProtectedRouteRoute: AdminProtectedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRoute: AppRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  MeusInteressesRoute: MeusInteressesRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  ProdutoresRoute: ProdutoresRoute,
  TermosUsoRoute: TermosUsoRoute,
  BeatSlugRoute: BeatSlugRoute,
  ProdutorSlugRoute: ProdutorSlugRoute,
  ProdutoraSlugRoute: ProdutoraSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
